### PR TITLE
Dual licensing, conan support and modern CMake

### PR DESCRIPTION
**Pull request by gergondet**
This PR brings the following changes:
- setup a dual license system: the original GPL-2 version is unchanged (and the default version of the library) and a BSD-2-Clause variant is introduced. In this version the GPL-2 code of SOLID is not integrated into the code, however the API/ABI should remain the same. The BSD-2-Clause variant cannot provide inter-penetration distance
- as a result, the `CD_Penetration/DT_TriEdge.h` is pulled from the public headers, I don't think this affects any code downstream (@jmirabel can you confirm this?)
- the PPA has been updated with 18.04 packages. The packages are built with the BSD-2-Clause variant
- Conan packaging support has been added

### CODE REVIEW

**Comment by jmirabel** [comment]
I didn't included `CD_Penetration/DT_TriEdge.h` myself but I have no idea whether it was included by means of recursion. I cannot have a look at it right now. I will later.

Thanks for the license change !

**Comment by gergondet** [comment]
@jmirabel in fact, it was included through `CD_Penetration/CD_Depth.h` which itself is also included through `CD/CD_Pair.h` (but there's no usage of `DT_TriEdge.h` classes in the public interace of `CD_Depth` itself.

If you wanna look for it `DT_TriEdge.h` defines three classes: (and two free functions that use them)
- `Depth_Edge`
- `Depth_Triangle`
- `Depth_TriangleStore`

I don't think they have much use beyond the inter-penetration depth computations.

**Comment by gergondet** [comment]
@jmirabel I'll merge this now as I need it to move forward with other PR, hopefully this won't cause any issue, otherwise I'll add a patch to install `DT_TriEdge.h` in the GPL version.

**Comment by jmirabel** [comment]
Sorry for the delay. I forgot about it. I confirm I have no issue with this change. Thanks for the license change.

**Pull request merged**
