### PR TITLE
CMake Package Config support added

### PR DESCRIPTION
**Pull request by ahundt**
see https://github.com/jrl-umi3218/jrl-cmakemodules/pull/103

### CODE REVIEW

**Comment by ahundt** [comment]
this is failing because the  jrl-umi3218/jrl-cmakemodules branch needs to be merged first so the submodule clone is failing, thus the cmake run won't work right

**Comment by ahundt** [comment]
@gergondet do you know what's going on with this [travis ci error](https://travis-ci.org/jrl-umi3218/sch-core/builds/170888632)? It seems to fail to check out a subrepository:
```

Submodule path 'tests/shared-tests': checked out '3b1a5b76465dcb7135b6dd30c6cb705df42ec817'
Unable to checkout '5e0e3a97b748aec181d01b666db44c938042a335' in submodule path 'cmake'
The command "eval git submodule update --init --recursive" failed. Retrying, 2 of 3.

```

**Comment by gergondet** [comment]
It indicates you pushed the wrong reference for the cmake submodule. (indeed `5e0e3a97b748aec181d01b666db44c938042a335` is not a valid reference but it is one for your fork)

My best guess is to do something like that in your local sch-core copy:
```bash
git submodule sync
cd cmake
git remote update
git checkout origin/master
cd ../
git commit -m 'Fix cmake submodule'
```

**Comment by ahundt** [comment]
okay hopefully fixed now!

**Comment by ahundt** [comment]
@gergondet can this be merged?

**Pull request merged**
